[tools]

adr-tools = "3.0.0"
golang = "1.24.12"
golangci-lint = "2.8.0"
goreleaser = "2.13.3"
hadolint = "2.14.0"
markdownlint-cli2 = "0.20.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
yamllint = "1.38.0"
yq = "4.50.1"
