[tools]

adr-tools = "3.0.0"
golang = "1.25.4"
golangci-lint = "2.5.0"
goreleaser = "2.9.0"
hadolint = "2.14.0"
markdownlint-cli2 = "0.18.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"
yamllint = "1.37.1"
yq = "4.48.1"
