[tools]

adr-tools = "3.0.0"
golang = "1.24.13"
golangci-lint = "2.10.1"
goreleaser = "2.14.1"
hadolint = "2.14.0"
markdownlint-cli2 = "0.21.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
yamllint = "1.38.0"
yq = "4.52.4"
