---
name: nix
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  test-go-versions:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['124', '125']
        os:
          - system: x86_64-linux
            runs-on: ubuntu-24.04
          - system: aarch64-darwin
            runs-on: macos-14
    runs-on: ${{ matrix.os.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Build with Go 1.${{ matrix.go-version }} on ${{ matrix.os.system }}
        run: nix build .#packages.${{ matrix.os.system }}.go-jsonschema-go${{ matrix.go-version }} --print-build-logs
      - name: Test with Go 1.${{ matrix.go-version }} on ${{ matrix.os.system }}
        run: nix build .#checks.${{ matrix.os.system }}.tests-go${{ matrix.go-version }} --print-build-logs
      - name: Upload coverage to Codecov
        if: matrix.go-version == '125' && matrix.os.system == 'x86_64-linux'
        uses: codecov/codecov-action@v5
        with:
          files: ./result/coverage.out
          fail_ci_if_error: false
  qa:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Run Nix flake checks
        run: nix flake check --print-build-logs --show-trace
